security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            access_token:
                token_handler: App\Security\ApiTokenAccessTokenHandler

        main:
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            lazy: true
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
            entry_point: form_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/donor, roles: ROLE_USER }
